'use strict';

module.exports = function(environment) {
  let ENV = {
    modulePrefix: 'star-wars-game-show-castings',
    environment,
    rootURL: '/',
    locationType: 'auto',

    gReCaptcha: {
      siteKey: '6LeOAEAUAAAAAC1wCXsJKhGyBVsM22DoFFLbVIkJ'
    },

    firebase: {
        apiKey: "AIzaSyBnjSnpCsPQPi8GyS6r23vLnuFv0loKtzs",
        authDomain: "star-wars-game-show-castings.firebaseapp.com",
        databaseURL: "https://star-wars-game-show-castings.firebaseio.com",
        projectId: "star-wars-game-show-castings",
        storageBucket: "star-wars-game-show-castings.appspot.com",
        messagingSenderId: "721752426381",
        appId: "1:721752426381:web:cf67210974736bf5411fc4"
    },
    // if using ember-cli-content-security-policy
    contentSecurityPolicy: {
      'script-src': "'self' 'unsafe-eval' apis.google.com",
      'frame-src': "'self' https://*.firebaseapp.com",
      'connect-src': "'self' wss://*.firebaseio.com https://*.googleapis.com"
    },

    torii: {  
       sessionServiceName: 'session'
    },

    common: {

      countries:[
        {code:"AF" ,curr:"USD",name:"Afghanistan"},
        {code:"AX" ,curr:"EUR",name:"Åland Islands"},
        {code:"AL" ,curr:"USD",name:"Albania"},
        {code:"DZ" ,curr:"USD",name:"Algeria"},
        {code:"AS" ,curr:"USD",name:"American Samoa"},
        {code:"AD" ,curr:"EUR",name:"Andorra"},
        {code:"AO" ,curr:"USD",name:"Angola"},
        {code:"AI" ,curr:"USD",name:"Anguilla"},
        {code:"AQ" ,curr:"USD",name:"Antarctica"},
        {code:"AG" ,curr:"USD",name:"Antigua and Barbuda"},
        {code:"AR" ,curr:"USD",name:"Argentina"},
        {code:"AM" ,curr:"USD",name:"Armenia"},
        {code:"AW" ,curr:"USD",name:"Aruba"},
        {code:"AU" ,curr:"AUD",name:"Australia"},
        {code:"AT" ,curr:"EUR",name:"Austria"},
        {code:"AZ" ,curr:"USD",name:"Azerbaijan"},
        {code:"BS" ,curr:"USD",name:"Bahamas"},
        {code:"BH" ,curr:"USD",name:"Bahrain"},
        {code:"BD" ,curr:"USD",name:"Bangladesh"},
        {code:"BB" ,curr:"USD",name:"Barbados"},
        {code:"BY" ,curr:"USD",name:"Belarus"},
        {code:"BE" ,curr:"EUR",name:"Belgium"},
        {code:"BZ" ,curr:"USD",name:"Belize"},
        {code:"BJ" ,curr:"USD",name:"Benin"},
        {code:"BM" ,curr:"USD",name:"Bermuda"},
        {code:"BT" ,curr:"USD",name:"Bhutan"},
        {code:"BO" ,curr:"USD",name:"Bolivia, Plurinational State of"},
        {code:"BQ" ,curr:"EUR",name:"Bonaire, Sint Eustatius and Saba"},
        {code:"BA" ,curr:"USD",name:"Bosnia and Herzegovina"},
        {code:"BW" ,curr:"USD",name:"Botswana"},
        {code:"BV" ,curr:"USD",name:"Bouvet Island"},
        {code:"BR" ,curr:"BRL",name:"Brazil"},
        {code:"IO" ,curr:"USD",name:"British Indian Ocean Territory"},
        {code:"BN" ,curr:"USD",name:"Brunei Darussalam"},
        {code:"BG" ,curr:"BGN",name:"Bulgaria"},
        {code:"BF" ,curr:"USD",name:"Burkina Faso"},
        {code:"BI" ,curr:"USD",name:"Burundi"},
        {code:"KH" ,curr:"USD",name:"Cambodia"},
        {code:"CM" ,curr:"USD",name:"Cameroon"},
        {code:"CA" ,curr:"CAD",name:"Canada"},
        {code:"CV" ,curr:"USD",name:"Cape Verde"},
        {code:"KY" ,curr:"USD",name:"Cayman Islands"},
        {code:"CF" ,curr:"USD",name:"Central African Republic"},
        {code:"TD" ,curr:"USD",name:"Chad"},
        {code:"CL" ,curr:"USD",name:"Chile"},
        {code:"CN" ,curr:"CNY",name:"China"},
        {code:"CX" ,curr:"USD",name:"Christmas Island"},
        {code:"CC" ,curr:"USD",name:"Cocos (Keeling) Islands"},
        {code:"CO" ,curr:"USD",name:"Colombia"},
        {code:"KM" ,curr:"USD",name:"Comoros"},
        {code:"CG" ,curr:"USD",name:"Congo"},
        {code:"CD" ,curr:"USD",name:"Congo, the Democratic Republic of the"},
        {code:"CK" ,curr:"USD",name:"Cook Islands"},
        {code:"CR" ,curr:"USD",name:"Costa Rica"},
        {code:"CI" ,curr:"USD",name:"Côte d'Ivoire"},
        {code:"HR" ,curr:"HRK",name:"Croatia"},
        {code:"CU" ,curr:"USD",name:"Cuba"},
        {code:"CW" ,curr:"USD",name:"Curaçao"},
        {code:"CY" ,curr:"EUR",name:"Cyprus"},
        {code:"CZ" ,curr:"CZK",name:"Czech Republic"},
        {code:"DK" ,curr:"USD",name:"Denmark"},
        {code:"DJ" ,curr:"USD",name:"Djibouti"},
        {code:"DM" ,curr:"USD",name:"Dominica"},
        {code:"DO" ,curr:"USD",name:"Dominican Republic"},
        {code:"EC" ,curr:"USD",name:"Ecuador"},
        {code:"EG" ,curr:"USD",name:"Egypt"},
        {code:"SV" ,curr:"USD",name:"El Salvador"},
        {code:"GQ" ,curr:"USD",name:"Equatorial Guinea"},
        {code:"ER" ,curr:"USD",name:"Eritrea"},
        {code:"EE" ,curr:"EUR",name:"Estonia"},
        {code:"ET" ,curr:"USD",name:"Ethiopia"},
        {code:"FK" ,curr:"USD",name:"Falkland Islands (Malvinas)"},
        {code:"FO" ,curr:"USD",name:"Faroe Islands"},
        {code:"FJ" ,curr:"USD",name:"Fiji"},
        {code:"FI" ,curr:"EUR",name:"Finland"},
        {code:"FR" ,curr:"EUR",name:"France"},
        {code:"GF" ,curr:"EUR",name:"French Guiana"},
        {code:"PF" ,curr:"EUR",name:"French Polynesia"},
        {code:"TF" ,curr:"EUR",name:"French Southern Territories"},
        {code:"GA" ,curr:"USD",name:"Gabon"},
        {code:"GM" ,curr:"USD",name:"Gambia"},
        {code:"GE" ,curr:"USD",name:"Georgia"},
        {code:"DE" ,curr:"EUR",name:"Germany"},
        {code:"GH" ,curr:"USD",name:"Ghana"},
        {code:"GI" ,curr:"USD",name:"Gibraltar"},
        {code:"GR" ,curr:"EUR",name:"Greece"},
        {code:"GL" ,curr:"USD",name:"Greenland"},
        {code:"GD" ,curr:"USD",name:"Grenada"},
        {code:"GP" ,curr:"EUR",name:"Guadeloupe"},
        {code:"GU" ,curr:"USD",name:"Guam"},
        {code:"GT" ,curr:"USD",name:"Guatemala"},
        {code:"GG" ,curr:"USD",name:"Guernsey"},
        {code:"GN" ,curr:"USD",name:"Guinea"},
        {code:"GW" ,curr:"USD",name:"Guinea-Bissau"},
        {code:"GY" ,curr:"USD",name:"Guyana"},
        {code:"HT" ,curr:"USD",name:"Haiti"},
        {code:"HM" ,curr:"USD",name:"Heard Island and McDonald Islands"},
        {code:"VA" ,curr:"EUR",name:"Holy See (Vatican City State)"},
        {code:"HN" ,curr:"USD",name:"Honduras"},
        {code:"HK" ,curr:"HKD",name:"Hong Kong"},
        {code:"HU" ,curr:"HUF",name:"Hungary"},
        {code:"IS" ,curr:"USD",name:"Iceland"},
        {code:"IN" ,curr:"INR",name:"India"},
        {code:"ID" ,curr:"IDR",name:"Indonesia"},
        {code:"IR" ,curr:"USD",name:"Iran, Islamic Republic of"},
        {code:"IQ" ,curr:"USD",name:"Iraq"},
        {code:"IE" ,curr:"EUR",name:"Ireland"},
        {code:"IM" ,curr:"USD",name:"Isle of Man"},
        {code:"IL" ,curr:"ILS",name:"Israel"},
        {code:"IT" ,curr:"EUR",name:"Italy"},
        {code:"JM" ,curr:"USD",name:"Jamaica"},
        {code:"JP" ,curr:"JPY",name:"Japan"},
        {code:"JE" ,curr:"USD",name:"Jersey"},
        {code:"JO" ,curr:"USD",name:"Jordan"},
        {code:"KZ" ,curr:"USD",name:"Kazakhstan"},
        {code:"KE" ,curr:"USD",name:"Kenya"},
        {code:"KI" ,curr:"USD",name:"Kiribati"},
        {code:"KP" ,curr:"USD",name:"Korea, Democratic People's Republic of"},
        {code:"KR" ,curr:"KRW",name:"Korea, Republic of"},
        {code:"KW" ,curr:"USD",name:"Kuwait"},
        {code:"KG" ,curr:"USD",name:"Kyrgyzstan"},
        {code:"LA" ,curr:"USD",name:"Lao People's Democratic Republic"},
        {code:"LV" ,curr:"EUR",name:"Latvia"},
        {code:"LB" ,curr:"USD",name:"Lebanon"},
        {code:"LS" ,curr:"USD",name:"Lesotho"},
        {code:"LR" ,curr:"USD",name:"Liberia"},
        {code:"LY" ,curr:"USD",name:"Libya"},
        {code:"LI" ,curr:"USD",name:"Liechtenstein"},
        {code:"LT" ,curr:"EUR",name:"Lithuania"},
        {code:"LU" ,curr:"EUR",name:"Luxembourg"},
        {code:"MO" ,curr:"USD",name:"Macao"},
        {code:"MK" ,curr:"USD",name:"Macedonia"},
        {code:"MG" ,curr:"USD",name:"Madagascar"},
        {code:"MW" ,curr:"USD",name:"Malawi"},
        {code:"MY" ,curr:"MYR",name:"Malaysia"},
        {code:"MV" ,curr:"USD",name:"Maldives"},
        {code:"ML" ,curr:"USD",name:"Mali"},
        {code:"MT" ,curr:"EUR",name:"Malta"},
        {code:"MH" ,curr:"USD",name:"Marshall Islands"},
        {code:"MQ" ,curr:"EUR",name:"Martinique"},
        {code:"MR" ,curr:"USD",name:"Mauritania"},
        {code:"MU" ,curr:"USD",name:"Mauritius"},
        {code:"YT" ,curr:"EUR",name:"Mayotte"},
        {code:"MX" ,curr:"MXN",name:"Mexico"},
        {code:"FM" ,curr:"USD",name:"Micronesia, Federated States of"},
        {code:"MD" ,curr:"USD",name:"Moldova, Republic of"},
        {code:"MC" ,curr:"USD",name:"Monaco"},
        {code:"MN" ,curr:"USD",name:"Mongolia"},
        {code:"ME" ,curr:"EUR",name:"Montenegro"},
        {code:"MS" ,curr:"USD",name:"Montserrat"},
        {code:"MA" ,curr:"USD",name:"Morocco"},
        {code:"MZ" ,curr:"USD",name:"Mozambique"},
        {code:"MM" ,curr:"USD",name:"Myanmar"},
        {code:"NA" ,curr:"USD",name:"Namibia"},
        {code:"NR" ,curr:"USD",name:"Nauru"},
        {code:"NP" ,curr:"USD",name:"Nepal"},
        {code:"NL" ,curr:"EUR",name:"Netherlands"},
        {code:"NC" ,curr:"USD",name:"New Caledonia"},
        {code:"NZ" ,curr:"NZD",name:"New Zealand"},
        {code:"NI" ,curr:"USD",name:"Nicaragua"},
        {code:"NE" ,curr:"USD",name:"Niger"},
        {code:"NG" ,curr:"USD",name:"Nigeria"},
        {code:"NU" ,curr:"USD",name:"Niue"},
        {code:"NF" ,curr:"USD",name:"Norfolk Island"},
        {code:"MP" ,curr:"USD",name:"Northern Mariana Islands"},
        {code:"NO" ,curr:"NOK",name:"Norway"},
        {code:"OM" ,curr:"USD",name:"Oman"},
        {code:"PK" ,curr:"USD",name:"Pakistan"},
        {code:"PW" ,curr:"USD",name:"Palau"},
        {code:"PS" ,curr:"USD",name:"Palestinian Territory, Occupied"},
        {code:"PA" ,curr:"USD",name:"Panama"},
        {code:"PG" ,curr:"USD",name:"Papua New Guinea"},
        {code:"PY" ,curr:"USD",name:"Paraguay"},
        {code:"PE" ,curr:"USD",name:"Peru"},
        {code:"PH" ,curr:"PHP",name:"Philippines"},
        {code:"PN" ,curr:"USD",name:"Pitcairn"},
        {code:"PL" ,curr:"PLN",name:"Poland"},
        {code:"PT" ,curr:"EUR",name:"Portugal"},
        {code:"PR" ,curr:"USD",name:"Puerto Rico"},
        {code:"QA" ,curr:"USD",name:"Qatar"},
        {code:"RE" ,curr:"USD",name:"Réunion"},
        {code:"RO" ,curr:"RON",name:"Romania"},
        {code:"RU" ,curr:"RUB",name:"Russian Federation"},
        {code:"RW" ,curr:"USD",name:"Rwanda"},
        {code:"BL" ,curr:"EUR",name:"Saint Barthélemy"},
        {code:"SH" ,curr:"USD",name:"Saint Helena, Ascension and Tristan da Cunha"},
        {code:"KN" ,curr:"USD",name:"Saint Kitts and Nevis"},
        {code:"LC" ,curr:"USD",name:"Saint Lucia"},
        {code:"MF" ,curr:"EUR",name:"Saint Martin (French part)"},
        {code:"PM" ,curr:"EUR",name:"Saint Pierre and Miquelon"},
        {code:"VC" ,curr:"USD",name:"Saint Vincent and the Grenadines"},
        {code:"WS" ,curr:"USD",name:"Samoa"},
        {code:"SM" ,curr:"EUR",name:"San Marino"},
        {code:"ST" ,curr:"USD",name:"Sao Tome and Principe"},
        {code:"SA" ,curr:"USD",name:"Saudi Arabia"},
        {code:"SN" ,curr:"USD",name:"Senegal"},
        {code:"RS" ,curr:"USD",name:"Serbia"},
        {code:"SC" ,curr:"USD",name:"Seychelles"},
        {code:"SL" ,curr:"USD",name:"Sierra Leone"},
        {code:"SG" ,curr:"SGD",name:"Singapore"},
        {code:"SX" ,curr:"USD",name:"Sint Maarten (Dutch part)"},
        {code:"SK" ,curr:"EUR",name:"Slovakia"},
        {code:"SI" ,curr:"EUR",name:"Slovenia"},
        {code:"SB" ,curr:"USD",name:"Solomon Islands"},
        {code:"SO" ,curr:"USD",name:"Somalia"},
        {code:"ZA" ,curr:"ZAR",name:"South Africa"},
        {code:"GS" ,curr:"USD",name:"South Georgia and the South Sandwich Islands"},
        {code:"SS" ,curr:"USD",name:"South Sudan"},
        {code:"ES" ,curr:"EUR",name:"Spain"},
        {code:"LK" ,curr:"USD",name:"Sri Lanka"},
        {code:"SD" ,curr:"USD",name:"Sudan"},
        {code:"SR" ,curr:"USD",name:"Suri,name"},
        {code:"SJ" ,curr:"USD",name:"Svalbard and Jan Mayen"},
        {code:"SZ" ,curr:"USD",name:"Swaziland"},
        {code:"SE" ,curr:"SEK",name:"Sweden"},
        {code:"CH" ,curr:"CHF",name:"Switzerland"},
        {code:"SY" ,curr:"USD",name:"Syrian Arab Republic"},
        {code:"TW" ,curr:"USD",name:"Taiwan, Province of China"},
        {code:"TJ" ,curr:"USD",name:"Tajikistan"},
        {code:"TZ" ,curr:"USD",name:"Tanzania, United Republic of"},
        {code:"TH" ,curr:"THB",name:"Thailand"},
        {code:"TL" ,curr:"USD",name:"Timor-Leste"},
        {code:"TG" ,curr:"USD",name:"Togo"},
        {code:"TK" ,curr:"USD",name:"Tokelau"},
        {code:"TO" ,curr:"USD",name:"Tonga"},
        {code:"TT" ,curr:"USD",name:"Trinidad and Tobago"},
        {code:"TN" ,curr:"USD",name:"Tunisia"},
        {code:"TR" ,curr:"TRY",name:"Turkey"},
        {code:"TM" ,curr:"USD",name:"Turkmenistan"},
        {code:"TC" ,curr:"USD",name:"Turks and Caicos Islands"},
        {code:"TV" ,curr:"USD",name:"Tuvalu"}, 
        {code:"UG" ,curr:"USD",name:"Uganda"},
        {code:"UA" ,curr:"USD",name:"Ukraine"},
        {code:"AE" ,curr:"USD",name:"United Arab Emirates"},
        {code:"GB" ,curr:"GBP",name:"United Kingdom"},
        {code:"US" ,curr:"USD",name:"United States"},
        {code:"UM" ,curr:"USD",name:"United States Minor Outlying Islands"},
        {code:"UY" ,curr:"USD",name:"Uruguay"},
        {code:"UZ" ,curr:"USD",name:"Uzbekistan"},
        {code:"VU" ,curr:"USD",name:"Vanuatu"},
        {code:"VE" ,curr:"USD",name:"Venezuela, Bolivarian Republic of"},
        {code:"VN" ,curr:"USD",name:"Viet Nam"},
        {code:"VG" ,curr:"USD",name:"Virgin Islands, British"},
        {code:"VI" ,curr:"USD",name:"Virgin Islands, U.S."},
        {code:"WF" ,curr:"USD",name:"Wallis and Futuna"},
        {code:"EH" ,curr:"USD",name:"Western Sahara"},
        {code:"YE" ,curr:"USD",name:"Yemen"},
        {code:"ZM" ,curr:"USD",name:"Zambia"},
        {code:"ZW" ,curr:"USD",name:"Zimbabwe"},      
      ], 

    },

    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. EMBER_NATIVE_DECORATOR_SUPPORT: true
      },
      EXTEND_PROTOTYPES: {
        // Prevent Ember Data from overriding Date.parse.
        Date: false
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
     ENV.APP.LOG_ACTIVE_GENERATION = true;
     ENV.APP.LOG_TRANSITIONS = true;
     ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
     ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
    ENV.APP.autoboot = false;
  }

  if (environment === 'production') {
    // here you can enable a production-specific feature
  }

  return ENV;
};
